### ISSUE TITLE
关于UMDF安装问题

### ISSUE THREAD

**Issue by fly55555** [lingme/Zonx-Virtual-Display#1]
驱动编译之后，使用inf安装，提示“第三方inf不包含数字签名信息”。
我想是因为测试签名不行吧，毕竟系统未处于 禁用签名强制 情况下。
后来我用了过期的签名，强行打上去，仍然不能安装，是一定需要
M$颁发的签名才可以吗?

**Comment by lingme** [comment]
Hello, 直接安装是安装不了的，你需要先信任生成的证书，然后安装才可以
